### ISSUE TITLE
.litematic export

### ISSUE THREAD

**Issue by Nikki-Devil** [d-002/dikc-8#2]
Is it possible to add an option to export the .litematic inside the compiler folder instead ?
The reason is that if we are using another launcher (like Prism for example) we would have to go search it
Another reason and the one I'm asking it is if we are using a non-Windows system like any Linux or MacOS system, it won't be able to export it right/at all

Also, in the README you should add that we need the litemapy library

**Comment by d-002** [comment]
As I said, I'm not focusing that much on this computer, because I want to concentrate on the newer version of it. However, I appreciate the work you have put into upgrading these files!

**Comment by d-002** [comment]
As I said, I'm not focusing that much on this computer, because I want to concentrate on the newer version of it. However, I appreciate the work you have put into upgrading these files!

**Comment by d-002** [comment]
I think I will add a GUI for better user interface, since you made me realize that these utilities are not user-friendly.

**Edit**: Added it.
